# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  python.version: '3.8'
  TF_CPP_MIN_LOG_LEVEL: 3  # tell XLA to be quiet
  JAX_PLATFORM_NAME: cpu

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    sudo apt install -y swig
    python -m pip install --upgrade pip wheel
    pip install -r requirements.txt
    pip install -r requirements.dev.txt
    pip install pytest-azurepipelines
  displayName: 'Install requirements'

- script: python -m flake8 coax
  displayName: 'Run flake8'

- script: python -m pytest coax -v
  displayName: 'Run pytest'

- script: |
    sudo apt install -y pandoc
    pip install -r requirements.doc.txt
    python setup.py build_sphinx
  displayName: 'Build docs'

- task: FtpUpload@2
  displayName: 'Deploy docs'
  inputs:
    credentialsOption: 'inputs'
    serverUrl: $(FTP_DEPLOY_SERVERURL)
    username: $(FTP_DEPLOY_USERNAME)
    password: $(FTP_DEPLOY_PASSWORD)
    rootDirectory: 'build/sphinx/html/'
    filePatterns: '**'
    remoteDirectory: '/site/wwwroot'
    clean: false
    cleanContents: true
    preservePaths: true
    trustSSL: false
